const fotoDefault = [
  "/assets/img/placeholder.webp",
];

const dataUMKM = [
  {
    id: 1,
    noUrut: 1,
    nama: "IRVAN SALIM",
    lokasi: "Dusun Krasak RT 01/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "PISAU, MESIN, GOBANG, DLL",
    rt: "01",
    rw: "02",
    koordinat: "-7.323070,109.915231",
    nomorHP: "085321005164",
    medsosMarketplace: "-",
    jamOperasional: "-",
    hariKerja: "-",
    keteranganTambahan: "-",
    foto: [
      "/assets/img/IRVAN/1.webp", 
    ],
  },
  {
    id: 2,
    noUrut: 2,
    nama: "A. ROZAK",
    lokasi: "Dusun Krasak RT 01/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "SABIT, PISAU DLL",
    rt: "01",
    rw: "02",
    koordinat: "-7.322504,109.916180",
    nomorHP: "-",
    medsosMarketplace: "-",
    jamOperasional: "07.00 - selesai",
    hariKerja: "Senin - Minggu",
    keteranganTambahan:
      "Produksi alat pertanian, penjualannya ada yang jemput, anaknya membantu masarin",
    foto: [
      "/assets/img/A_ROZAK/1.webp",
      "/assets/img/A_ROZAK/2.webp",
      "/assets/img/A_ROZAK/3.webp",
      "/assets/img/A_ROZAK/5.webp",
      "/assets/img/A_ROZAK/6.webp",
    ],
  },
  {
    id: 3,
    noUrut: 3,
    nama: "MUHAMAD MUHSON",
    lokasi: "Dusun Krasak RT 01/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "CANGKUL",
    rt: "01",
    rw: "02",
    koordinat: "-7.321032,109.916532",
    nomorHP: "081328478122",
    medsosMarketplace: "-",
    jamOperasional: "06.00 - selesai",
    hariKerja: "Senin - Minggu",
    keteranganTambahan:
      "Komplit, bisa request pesanan, penjualan ke petani langsung",
    foto: [
      "/assets/img/MUHAMAD_MUHSON/1.webp",
      "/assets/img/MUHAMAD_MUHSON/2.webp",
      "/assets/img/MUHAMAD_MUHSON/3.webp",
      "/assets/img/MUHAMAD_MUHSON/4.webp",
    ],
  },
  {
    id: 4,
    noUrut: 4,
    nama: "WAHID SALMAN",
    lokasi: "Dusun Krasak RT 02/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "GAGANG, PISAU DLL",
    rt: "02",
    rw: "02",
    koordinat: "-7.322554,109.916163",
    nomorHP: "081328478122",
    medsosMarketplace: "Whatsapp",
    jamOperasional: "08.00 - 16.00",
    hariKerja: "Senin - Minggu",
    keteranganTambahan: "Penjualan di Pasar Garung, bahan baku dari besi dan drum bekas",
    foto: [
      "/assets/img/WAHID_SALMAN/1.webp",
      "/assets/img/WAHID_SALMAN/2.webp",
      "/assets/img/WAHID_SALMAN/3.webp",
      "/assets/img/WAHID_SALMAN/4.webp",
    ],
  },
  {
    id: 5,
    noUrut: 5,
    nama: "MUSMAN",
    lokasi: "Dusun Krasak RT 02/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "KOMPOR, LAS, DLL",
    rt: "02",
    rw: "02",
    koordinat: "-7.322332,109.915233",
    nomorHP: "-",
    medsosMarketplace: "-",
    jamOperasional: "08.00 - 16.00",
    hariKerja: "Senin - Minggu",
    keteranganTambahan: "-",
    foto: [
      "/assets/img/MUSMAN/1.jpeg",
      "/assets/img/MUSMAN/2.jpeg",
    ]
  },
  {
    id: 6,
    noUrut: 6,
    nama: "MUHAMAD TAMBAH",
    lokasi: "Dusun Krasak RT 04/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "LAS",
    rt: "04",
    rw: "02",
    koordinat: "-7.3227549,109.9165808",
    nomorHP: "085228211939",
    medsosMarketplace: "-",
    jamOperasional: "07.00-12.00",
    hariKerja: "Senin - Minggu",
    keteranganTambahan: "-",
    foto: fotoDefault,
  },
  {
    id: 7,
    noUrut: 7,
    nama: "MUSLICH",
    lokasi: "Dusun Krasak RT 04/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "KERUK, DLL",
    rt: "04",
    rw: "02",
    koordinat: "-7.3225753,109.9169774",
    nomorHP: "081328905722",
    medsosMarketplace: "-",
    jamOperasional: "07.00-12.00",
    hariKerja: "Senin - Minggu",
    keteranganTambahan: "-",
    foto: fotoDefault,
  },
  {
    id: 8,
    noUrut: 8,
    nama: "MAHMUD",
    lokasi: "Dusun Krasak RT 04/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "LAS",
    rt: "04",
    rw: "02",
    koordinat: "-7.3224828,109.9169244",
    nomorHP: "085199121915",
    medsosMarketplace:
      "youtube : (https://youtube.com/@zayworkshop?si=wFx6ROaqI7jqWb3T)",
    jamOperasional: "-",
    hariKerja: "Senin - Minggu",
    keteranganTambahan:
      "Membuat mesin, pisau rajang tembakau, dan mempunyai distributornya sendiri",
    foto: fotoDefault,
  },
  {
    id: 9,
    noUrut: 9,
    nama: "NASROH",
    lokasi: "Dusun Krasak RT 04/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "SABIT, CANGKUL",
    rt: "04",
    rw: "02",
    koordinat: "-7.3227439,109.9164949",
    nomorHP: "0895324108549",
    medsosMarketplace: "-",
    jamOperasional: "07.30-12.00",
    hariKerja: "Senin - Minggu (kadang tidak setiap hari)",
    keteranganTambahan: "-",
    foto: fotoDefault,
  },
  {
    id: 10,
    noUrut: 10,
    nama: "ARMAN",
    lokasi: "Dusun Krasak RT 04/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "SABIT, CANGKUL",
    rt: "04",
    rw: "02",
    koordinat: "-7.3217290,109.9154529",
    nomorHP: "081338345441",
    medsosMarketplace: "-",
    jamOperasional: "07.00-13.00",
    hariKerja: "Senin - Minggu",
    keteranganTambahan: "-",
    foto: [
      "/assets/img/ARMAN/2.webp",
      "/assets/img/ARMAN/3.webp",
      "/assets/img/ARMAN/4.webp",
      "/assets/img/ARMAN/5.webp",
    ],
  },
  {
    id: 11,
    noUrut: 11,
    nama: "MUHAMAD FADIL",
    lokasi: "Dusun Krasak RT 05/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "CANGKUL, DLL",
    rt: "05",
    rw: "02",
    koordinat: "-7.3214260,109.9167464",
    nomorHP: "081392097188",
    medsosMarketplace: "-",
    jamOperasional: "fleksibel",
    hariKerja: "Senin - Minggu",
    keteranganTambahan: "Punya distributor sendiri",
    foto: fotoDefault,
  },
  {
    id: 12,
    noUrut: 12,
    nama: "ZAENUN",
    lokasi: "Dusun Krasak RT 07/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "SABIT, CANDUNG",
    rt: "07",
    rw: "02",
    koordinat: "-7.3234189,109.9164379",
    nomorHP: "082324490969",
    medsosMarketplace: "pakai relasi lewat telfon",
    jamOperasional: "08:00 - 16:00",
    hariKerja: "5-7 hari",
    keteranganTambahan: "-",
    foto: [
      "/assets/img/ZAENUN/1.webp",
      "/assets/img/ZAENUN/2.webp",
      "/assets/img/ZAENUN/3.webp",
      "/assets/img/ZAENUN/4.webp",
    ],
  },
  {
    id: 13,
    noUrut: 13,
    nama: "MUCHSON",
    lokasi: "Dusun Krasak RT 06/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "CANGKUL, DLL",
    rt: "06",
    rw: "02",
    koordinat: "-7.3210246,109.9165650",
    nomorHP: "081325418247",
    medsosMarketplace: "-",
    jamOperasional: "08:00 - selesai",
    hariKerja: "3-5 hari",
    keteranganTambahan:
      "Udah pakai mesin, ngider-ngiderin sendiri, langsung telfon, pesenannya sesuai request",
    foto: [
      "/assets/img/MUCHSON/1.webp",
    ],
  },
  {
    id: 14,
    noUrut: 14,
    nama: "MUHSENG",
    lokasi: "Dusun Krasak RT 06/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "ARIT",
    rt: "06",
    rw: "02",
    koordinat: "-7.3213861,109.9156956",
    nomorHP: "-",
    medsosMarketplace: "ngiderin ke jawa barat",
    jamOperasional: "05:30 - selasai",
    hariKerja: "Senin - Minggu",
    keteranganTambahan: "Sebulan sekali ke jawa barat",
    foto: [
      "/assets/img/MUHSENG/1.webp",
      "/assets/img/MUHSENG/3.webp",
      "/assets/img/MUHSENG/4.webp",
      "/assets/img/MUHSENG/5.webp",
    ],
  },
  {
    id: 15,
    noUrut: 15,
    nama: "BASUKI",
    lokasi: "Dusun Krasak RT 06/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "ARIT, PISAU, GOBANG, CANGKUL",
    rt: "06",
    rw: "02",
    koordinat: "-7.321318,109.915762",
    nomorHP: "082137999725",
    medsosMarketplace: "facebook, relasi",
    jamOperasional: "06:00 - selesai",
    hariKerja: "Senin - Minggu",
    keteranganTambahan:
      "Membuat sesuai pesanan dan bahan-bahannya impor dari luar negeri",
    foto: [
      "/assets/img/BASUKI/2.webp",
      "/assets/img/BASUKI/3.webp",
      "/assets/img/BASUKI/4.webp",
      "/assets/img/BASUKI/5.webp",
      "/assets/img/BASUKI/6.webp",
    ],
  },
  {
    id: 16,
    noUrut: 16,
    nama: "SUBHAN",
    lokasi: "Dusun Krasak RT 06/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "ARIT",
    rt: "06",
    rw: "02",
    koordinat: "-7.3216312,109.9155907",
    nomorHP: "-",
    medsosMarketplace: "-",
    jamOperasional: "07:00-13:00",
    hariKerja: "4-7 hari",
    keteranganTambahan:
      "Ngiderin sendiri ke Pasar Semarang, Banyuwangi, dan Jawa Timur",
    foto: [
      "/assets/img/SUBHAN/1.webp",
      "/assets/img/SUBHAN/2.webp",
      "/assets/img/SUBHAN/3.webp",
      "/assets/img/SUBHAN/4.webp",
      "/assets/img/SUBHAN/5.webp",
    ],
  },
  {
    id: 17,
    noUrut: 17,
    nama: "MUJIB SANTOSO",
    lokasi: "Dusun Krasak RT 06/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "ARIT, SABIT",
    rt: "06",
    rw: "02",
    koordinat: "-7.3211510,109.9169244",
    nomorHP: "-",
    medsosMarketplace: "pake shopee sm tiktok",
    jamOperasional: "08:00 - 13:00",
    hariKerja: "4-5 hari",
    keteranganTambahan:
      "Pakai manual, pemasarannya online tapi kenak blokir terus karena menjual senjata tajam juga kadang ada yg minta refund dan barang yg dikembalikan bekas",
    foto: [
      "/assets/img/MUJIB/1.webp",
      "/assets/img/MUJIB/2.webp",
      "/assets/img/MUJIB/3.webp",
    ],
  },
  {
    id: 18,
    noUrut: 18,
    nama: "AHMAD",
    lokasi: "Dusun Krasak RT 06/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "ARIT, CANGKUL",
    rt: "06",
    rw: "02",
    koordinat: "-7.3217213,109.9155226",
    nomorHP: "-",
    medsosMarketplace: "ada bakulnya sendiri",
    jamOperasional: "07:00 - 13:00",
    hariKerja: "Senin - Minggu",
    keteranganTambahan:
      "Pesenannya melalui telfon, request, masarinnya sampai ke Muntilan",
    foto: fotoDefault,
  },
  {
    id: 19,
    noUrut: 19,
    nama: "NOVI",
    lokasi: "Dusun Krasak RT 07/RW 02",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "GOBANG, ALAT PERTANIAN",
    rt: "07",
    rw: "02",
    koordinat: "-7.3238067,109.9163907",
    nomorHP: "082327676661",
    medsosMarketplace: "lewat telfon kadang tiktok sama facebook",
    jamOperasional: "09:00 - selesai",
    hariKerja: "Gak pasti",
    keteranganTambahan:
      "Pesenannya ada di sekitar Jateng seperti Tulungagung, Temanggung, Magelang, dan barangnya impor dari luar negeri",
    foto: [
      "/assets/img/NOVI/1.webp",
      "/assets/img/NOVI/2.webp",
      "/assets/img/NOVI/3.webp",
    ],
  },
  {
    id: 20,
    noUrut: 20,
    nama: "AMILIN RANU RIZAL",
    lokasi: "Dusun Krasak RT 01/RW 04",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "LAS",
    rt: "01",
    rw: "04",
    koordinat: "-7.322493,109.915808",
    nomorHP: "-",
    medsosMarketplace: "fb : jalu imdad",
    jamOperasional: "7 - 4 (tergantung ramai/gak)",
    hariKerja: "Senin - Minggu",
    keteranganTambahan: "Nganggur kalau gak ada order masuk",
    foto: [
      "/assets/img/AMILIN/1.webp", 
    ],
  },
  {
    id: 21,
    noUrut: 21,
    nama: "MAS`UD",
    lokasi: "Dusun Krasak RT 02/RW 04",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "KARAH",
    rt: "02",
    rw: "04",
    koordinat: "-7.323194,109.915954",
    nomorHP: "08999913176",
    medsosMarketplace: "-",
    jamOperasional: "Fleksibel",
    hariKerja: "-",
    keteranganTambahan: "-",
    foto: fotoDefault,
  },
  {
    id: 22,
    noUrut: 22,
    nama: "MUKHTAS",
    lokasi: "Dusun Krasak RT 02/RW 04",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "LAS, TRALIS",
    rt: "02",
    rw: "04",
    koordinat: "-7.323304,109.915175",
    nomorHP: "081385881843",
    medsosMarketplace: "-",
    jamOperasional: "Fleksibel",
    hariKerja: "Fleksibel",
    keteranganTambahan: "-",
    foto: fotoDefault,
  },
  {
    id: 23,
    noUrut: 23,
    nama: "ABDUL NGAZIS",
    lokasi: "Dusun Krasak RT 02/RW 04",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "ANGKLO/ALAT BAKAR",
    rt: "02",
    rw: "04",
    koordinat: "-7.323377,109.915759",
    nomorHP: "082224212643",
    medsosMarketplace: "-",
    jamOperasional: "-",
    hariKerja: "-",
    keteranganTambahan: "-",
    foto: [
      "/assets/img/NGAZIZ/1.webp", 
    ],
  },
  {
    id: 24,
    noUrut: 24,
    nama: "MUHAMMAD AHSIN",
    lokasi: "Dusun Krasak RT 02/RW 04",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "CINCIN/RING CANGKUL",
    rt: "02",
    rw: "04",
    koordinat: "-7.323337,109.915182",
    nomorHP: "081390825004",
    medsosMarketplace: "-",
    jamOperasional: "-",
    hariKerja: "-",
    keteranganTambahan: "-",
    foto: [
      "/assets/img/AHSIN/1.webp", 
    ],
  },
  {
    id: 25,
    noUrut: 25,
    nama: "AHMAD UMAR",
    lokasi: "Dusun Krasak RT 03/RW 04",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "SABIT",
    rt: "03",
    rw: "04",
    koordinat: "-7.321348,109.914743",
    nomorHP: "082234867524",
    medsosMarketplace: "-",
    jamOperasional: "08.00-16.00",
    hariKerja: "Senin - Minggu",
    keteranganTambahan: "Tutup jika berkeliling pemasaran",
    foto: [
      "/assets/img/AHMAD_UMAR/1.jpg",
    ],
  },
  {
    id: 26,
    noUrut: 26,
    nama: "AHMAD LATIF",
    lokasi: "Dusun Krasak RT 03/RW 04",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "SABIT, BENDO, PISAU, CANGKUL",
    rt: "03",
    rw: "04",
    koordinat: "-7.321761,109.914248",
    nomorHP: "081216252704",
    medsosMarketplace: "-",
    jamOperasional: "08.00-16.00",
    hariKerja: "Senin - Minggu",
    keteranganTambahan: "-",
    foto: [
      "/assets/img/AHMAD_LATIF/1.webp",
    ]
  },
  {
    id: 27,
    noUrut: 27,
    nama: "ANDRI FIADI",
    lokasi: "Dusun Krasak RT 03/RW 04",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "CANGKUL",
    rt: "03",
    rw: "04",
    koordinat: "-7.322446,109.914611",
    nomorHP: "085624067497",
    medsosMarketplace: "-",
    jamOperasional: "07.00-15.00",
    hariKerja: "Senin - Minggu",
    keteranganTambahan: "Pembuatan menggunakan mesin",
    foto: fotoDefault,
  },
  {
    id: 28,
    noUrut: 28,
    nama: "WARNO",
    lokasi: "Dusun Krasak RT 03/RW 04",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "GOBANG",
    rt: "03",
    rw: "04",
    koordinat: "-7.322153,109.914060",
    nomorHP: "0882005605962",
    medsosMarketplace: "-",
    jamOperasional: "08.00-15.00",
    hariKerja: "Senin - Minggu",
    keteranganTambahan: "Seminggu 4 hari",
    foto: fotoDefault,
  },
  {
    id: 29,
    noUrut: 29,
    nama: "MULYONO",
    lokasi: "Dusun Krasak RT 03/RW 04",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "SABIT, CANGKUL",
    rt: "03",
    rw: "04",
    koordinat: "-7.321684,109.913737",
    nomorHP: "-",
    medsosMarketplace: "-",
    jamOperasional: "08.00-16.00",
    hariKerja: "Senin - Minggu",
    keteranganTambahan: "Membuat gobang kalo ada event",
    foto: [
      "/assets/img/MULYONO/1.jpg",
    ],
  },
  {
    id: 30,
    noUrut: 30,
    nama: "SUNARWAN",
    lokasi: "Dusun Krasak RT 03/RW 04",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "CANGKUL",
    rt: "03",
    rw: "04",
    koordinat: "-7.322446,109.914611",
    nomorHP: "082228883523",
    medsosMarketplace: "-",
    jamOperasional: "07.00-17.00",
    hariKerja: "4 hari sekali",
    keteranganTambahan: "Pemasaran di Pasar Batur",
    foto: fotoDefault,
  },
  {
    id: 31,
    noUrut: 31,
    nama: "AGUS SUBUR",
    lokasi: "Dusun Krasak RT 03/RW 04",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "CANGKUL BERBAGAI UKURAN",
    rt: "03",
    rw: "04",
    koordinat: "-7.321573,109.914082",
    nomorHP: "0895336989121",
    medsosMarketplace: "tiktok : @agussbur56",
    jamOperasional: "06.00-16.00",
    hariKerja: "-",
    keteranganTambahan: "Buka dan produksi jika ada pesanan",
    foto: [
      "/assets/img/AGUS_SUBUR/1.jpg",
    ],
  },
  {
    id: 32,
    noUrut: 32,
    nama: "AHMAD PUJI SYUKUR",
    lokasi: "Dusun Krasak RT 03/RW 04",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "SABIT, CANGKUL",
    rt: "03",
    rw: "04",
    koordinat: "-7.321446,109.914275",
    nomorHP: "08324893199",
    medsosMarketplace: "-",
    jamOperasional: "07.00-15.00",
    hariKerja: "libur jumat",
    keteranganTambahan: "Bisa tidak libur jika ada pesanan",
    foto: [
      "/assets/img/PUJI_SYUKUR/1.jpg",
    ],
  },
  {
    id: 33,
    noUrut: 33,
    nama: "ROFIK JOKO",
    lokasi: "Dusun Krasak RT 04/RW 04",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "GOBANG, MESIN DLL",
    rt: "04",
    rw: "04",
    koordinat: "-7.322755,109.914617",
    nomorHP: "081391317703",
    medsosMarketplace: "-",
    jamOperasional: "08.00-15.30",
    hariKerja: "Senin - Minggu",
    keteranganTambahan: "-",
    foto: fotoDefault,
  },
  {
    id: 34,
    noUrut: 34,
    nama: "MUSBAH",
    lokasi: "Dusun Krasak RT 03/RW 04",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "SABIT, CANGKUL",
    rt: "03",
    rw: "04",
    koordinat: "-7.321681,109.914244",
    nomorHP: "089527154410",
    medsosMarketplace: "-",
    jamOperasional: "08.00-16.00",
    hariKerja: "Senin - Minggu",
    keteranganTambahan: "-",
    foto: [
      "/assets/img/MUSBAH/1.webp",
      "/assets/img/MUSBAH/3.webp",
      "/assets/img/MUSBAH/4.webp",
    ],
  },
  {
    id: 35,
    noUrut: 35,
    nama: "MUTOAN",
    lokasi: "Dusun Krasak RT 03/RW 04",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "CANGKUL, SABIT, PISAU",
    rt: "03",
    rw: "04",
    koordinat: "-7.321732,109.913826",
    nomorHP: "085228920999",
    medsosMarketplace: "-",
    jamOperasional: "08.00-16.00",
    hariKerja: "Senin - Minggu",
    keteranganTambahan: "-",
    foto: [
      "/assets/img/MUTOAN/3.webp",
      "/assets/img/MUTOAN/4.webp",
      "/assets/img/MUTOAN/5.webp",
      "/assets/img/MUTOAN/6.webp",
      "/assets/img/MUTOAN/7.webp",
    ],
  },
  {
    id: 36,
    noUrut: 36,
    nama: "AHMAD SOLIHIN",
    lokasi: "Dusun Krasak RT 03/RW 04",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "KARAH",
    rt: "03",
    rw: "04",
    koordinat: "-7.322083,109.914478",
    nomorHP: "-",
    medsosMarketplace: "-",
    jamOperasional: "08.00-16.00",
    hariKerja: "Senin - Minggu",
    keteranganTambahan: "-",
    foto: [
      "/assets/img/AHMAD_SOLIHIN/1.webp", 
    ],
  },
  {
    id: 37,
    noUrut: 37,
    nama: "SUYONO",
    lokasi: "Dusun Krasak RT 03/RW 04",
    pekerjaan: "Tukang Las / Pandai Besi",
    jenisProduksi: "MESIN ALAT PERTANIAN",
    rt: "03",
    rw: "04",
    koordinat: "-7.322511,109.914490",
    nomorHP: "081235870771",
    medsosMarketplace: "-",
    jamOperasional: "08.00-17.00",
    hariKerja: "jumat pagi libur",
    keteranganTambahan: "-",
    foto: [
      "/assets/img/SUYONO/1.jpg", 
    ],
  },
];
