const dataUMKM = [
  {
    id: 1,
    namaUsaha: "Pandai Besi Pak Sardi",
    namaPemilik: "Pak Sardi",
    lokasi: "Dusun Krasak, RT 01/RW 02",
    gmaps: "https://maps.google.com/",
    foto: "assets/img/umkm-placeholder.svg",
    kontakWA: "6281234567801",
    jamOperasional: "08.00 - 16.00 WIB",
    statusToko: "Buka setiap hari",
    medsos: {
      instagram: "-",
      facebook: "-",
      tiktok: "-"
    },
    keunggulan: "Menerima pembuatan dan perbaikan alat pertanian dengan hasil kuat dan rapi.",
    alat: ["Tungku pembakaran", "Palu", "Landasan besi", "Gerinda", "Mesin blower"],
    produk: ["Cangkul", "Sabit", "Pisau", "Arit"],
    keterangan: "Usaha pandai besi rumahan yang melayani kebutuhan alat pertanian masyarakat sekitar.",
    posisiTop: "36%",
    posisiLeft: "43%"
  },
  {
    id: 2,
    namaUsaha: "Pandai Besi Pak Warto",
    namaPemilik: "Pak Warto",
    lokasi: "Dusun Krasak, RT 01/RW 02",
    gmaps: "https://maps.google.com/",
    foto: "assets/img/umkm-placeholder.svg",
    kontakWA: "6281234567802",
    jamOperasional: "08.00 - 16.00 WIB",
    statusToko: "Buka setiap hari",
    medsos: {
      instagram: "-",
      facebook: "-",
      tiktok: "-"
    },
    keunggulan: "Produk alat pertanian dibuat sesuai kebutuhan pelanggan.",
    alat: ["Tungku", "Palu besar", "Landasan", "Gerinda tangan"],
    produk: ["Cangkul", "Parang", "Sabit"],
    keterangan: "UMKM pandai besi yang fokus pada alat pertanian dan peralatan rumah tangga berbahan besi.",
    posisiTop: "42%",
    posisiLeft: "51%"
  },
  {
    id: 3,
    namaUsaha: "Pandai Besi Pak Karto",
    namaPemilik: "Pak Karto",
    lokasi: "Dusun Krasak, RT 02/RW 02",
    gmaps: "https://maps.google.com/",
    foto: "assets/img/umkm-placeholder.svg",
    kontakWA: "6281234567803",
    jamOperasional: "08.00 - 16.00 WIB",
    statusToko: "Buka setiap hari",
    medsos: {
      instagram: "-",
      facebook: "-",
      tiktok: "-"
    },
    keunggulan: "Mampu memperbaiki alat lama agar dapat digunakan kembali.",
    alat: ["Tungku pembakaran", "Palu", "Penjepit besi", "Gerinda"],
    produk: ["Sabit", "Pisau dapur", "Cangkul"],
    keterangan: "Usaha ini melayani pembuatan baru dan servis alat pertanian.",
    posisiTop: "48%",
    posisiLeft: "60%"
  },
  {
    id: 4,
    namaUsaha: "Pandai Besi Pak Joko",
    namaPemilik: "Pak Joko",
    lokasi: "Dusun Krasak, RT 02/RW 03",
    gmaps: "https://maps.google.com/",
    foto: "assets/img/umkm-placeholder.svg",
    kontakWA: "6281234567804",
    jamOperasional: "08.00 - 16.00 WIB",
    statusToko: "Buka setiap hari",
    medsos: {
      instagram: "-",
      facebook: "-",
      tiktok: "-"
    },
    keunggulan: "Pengerjaan cepat dengan bentuk alat yang dapat disesuaikan.",
    alat: ["Tungku", "Palu", "Landasan besi", "Mesin potong"],
    produk: ["Cangkul", "Arit", "Pisau"],
    keterangan: "Pandai besi lokal yang membantu kebutuhan alat kerja masyarakat desa.",
    posisiTop: "55%",
    posisiLeft: "47%"
  },
  {
    id: 5,
    namaUsaha: "Pandai Besi Pak Slamet",
    namaPemilik: "Pak Slamet",
    lokasi: "Dusun Krasak, RT 03/RW 03",
    gmaps: "https://maps.google.com/",
    foto: "assets/img/umkm-placeholder.svg",
    kontakWA: "6281234567805",
    jamOperasional: "08.00 - 16.00 WIB",
    statusToko: "Buka setiap hari",
    medsos: {
      instagram: "-",
      facebook: "-",
      tiktok: "-"
    },
    keunggulan: "Hasil tempa kuat dan cocok untuk pekerjaan pertanian.",
    alat: ["Tungku pembakaran", "Blower", "Palu", "Landasan"],
    produk: ["Cangkul", "Sabit", "Golok"],
    keterangan: "Usaha pandai besi yang masih mempertahankan teknik tempa tradisional.",
    posisiTop: "63%",
    posisiLeft: "58%"
  },
  {
    id: 6,
    namaUsaha: "Pandai Besi Pak Darto",
    namaPemilik: "Pak Darto",
    lokasi: "Dusun Krasak, RT 03/RW 04",
    gmaps: "https://maps.google.com/",
    foto: "assets/img/umkm-placeholder.svg",
    kontakWA: "6281234567806",
    jamOperasional: "08.00 - 16.00 WIB",
    statusToko: "Buka setiap hari",
    medsos: {
      instagram: "-",
      facebook: "-",
      tiktok: "-"
    },
    keunggulan: "Melayani pesanan alat sesuai ukuran yang diminta.",
    alat: ["Tungku", "Gerinda", "Bor", "Palu"],
    produk: ["Pisau", "Cangkul", "Arit"],
    keterangan: "UMKM pandai besi dengan layanan pembuatan dan perbaikan alat.",
    posisiTop: "68%",
    posisiLeft: "38%"
  },
  {
    id: 7,
    namaUsaha: "Pandai Besi Pak Tono",
    namaPemilik: "Pak Tono",
    lokasi: "Dusun Krasak, RT 04/RW 04",
    gmaps: "https://maps.google.com/",
    foto: "assets/img/umkm-placeholder.svg",
    kontakWA: "6281234567807",
    jamOperasional: "08.00 - 16.00 WIB",
    statusToko: "Buka setiap hari",
    medsos: {
      instagram: "-",
      facebook: "-",
      tiktok: "-"
    },
    keunggulan: "Harga terjangkau untuk kebutuhan warga sekitar.",
    alat: ["Tungku", "Palu", "Landasan", "Mesin blower"],
    produk: ["Sabit", "Parang", "Pisau"],
    keterangan: "Usaha ini menjadi salah satu tempat pembuatan alat pertanian di wilayah dusun.",
    posisiTop: "31%",
    posisiLeft: "66%"
  },
  {
    id: 8,
    namaUsaha: "Pandai Besi Pak Mulyo",
    namaPemilik: "Pak Mulyo",
    lokasi: "Dusun Krasak, RT 04/RW 05",
    gmaps: "https://maps.google.com/",
    foto: "assets/img/umkm-placeholder.svg",
    kontakWA: "6281234567808",
    jamOperasional: "08.00 - 16.00 WIB",
    statusToko: "Buka setiap hari",
    medsos: {
      instagram: "-",
      facebook: "-",
      tiktok: "-"
    },
    keunggulan: "Mampu membuat alat dengan model tradisional maupun modern.",
    alat: ["Gerinda", "Tungku", "Palu", "Mesin potong"],
    produk: ["Cangkul", "Golok", "Pisau"],
    keterangan: "UMKM ini memproduksi alat kerja berbahan besi untuk masyarakat sekitar.",
    posisiTop: "25%",
    posisiLeft: "53%"
  },
  {
    id: 9,
    namaUsaha: "Pandai Besi Pak Bambang",
    namaPemilik: "Pak Bambang",
    lokasi: "Dusun Krasak, RT 05/RW 05",
    gmaps: "https://maps.google.com/",
    foto: "assets/img/umkm-placeholder.svg",
    kontakWA: "6281234567809",
    jamOperasional: "08.00 - 16.00 WIB",
    statusToko: "Buka setiap hari",
    medsos: {
      instagram: "-",
      facebook: "-",
      tiktok: "-"
    },
    keunggulan: "Produk kuat dan dapat dipesan sesuai kebutuhan.",
    alat: ["Tungku", "Blower", "Palu", "Landasan"],
    produk: ["Sabit", "Cangkul", "Arit"],
    keterangan: "Pandai besi yang melayani kebutuhan alat pertanian harian.",
    posisiTop: "72%",
    posisiLeft: "70%"
  },
  {
    id: 10,
    namaUsaha: "Pandai Besi Pak Roni",
    namaPemilik: "Pak Roni",
    lokasi: "Dusun Krasak, RT 05/RW 06",
    gmaps: "https://maps.google.com/",
    foto: "assets/img/umkm-placeholder.svg",
    kontakWA: "6281234567810",
    jamOperasional: "08.00 - 16.00 WIB",
    statusToko: "Buka setiap hari",
    medsos: {
      instagram: "-",
      facebook: "-",
      tiktok: "-"
    },
    keunggulan: "Melayani perbaikan alat rusak dan pembuatan baru.",
    alat: ["Tungku pembakaran", "Palu", "Penjepit", "Gerinda"],
    produk: ["Pisau", "Sabit", "Parang"],
    keterangan: "UMKM ini membantu warga memperbaiki alat pertanian yang sudah aus.",
    posisiTop: "59%",
    posisiLeft: "75%"
  },
  {
    id: 11,
    namaUsaha: "Pandai Besi Pak Hadi",
    namaPemilik: "Pak Hadi",
    lokasi: "Dusun Krasak, RT 06/RW 06",
    gmaps: "https://maps.google.com/",
    foto: "assets/img/umkm-placeholder.svg",
    kontakWA: "6281234567811",
    jamOperasional: "08.00 - 16.00 WIB",
    statusToko: "Buka setiap hari",
    medsos: {
      instagram: "-",
      facebook: "-",
      tiktok: "-"
    },
    keunggulan: "Pengerjaan teliti dengan bahan besi pilihan.",
    alat: ["Tungku", "Palu", "Landasan", "Gerinda"],
    produk: ["Cangkul", "Pisau", "Sabit"],
    keterangan: "Usaha rumahan yang berfokus pada pembuatan alat pertanian.",
    posisiTop: "44%",
    posisiLeft: "77%"
  },
  {
    id: 12,
    namaUsaha: "Pandai Besi Pak Rudi",
    namaPemilik: "Pak Rudi",
    lokasi: "Dusun Krasak, RT 06/RW 07",
    gmaps: "https://maps.google.com/",
    foto: "assets/img/umkm-placeholder.svg",
    kontakWA: "6281234567812",
    jamOperasional: "08.00 - 16.00 WIB",
    statusToko: "Buka setiap hari",
    medsos: {
      instagram: "-",
      facebook: "-",
      tiktok: "-"
    },
    keunggulan: "Bisa menerima pesanan alat dalam jumlah kecil maupun sedang.",
    alat: ["Tungku", "Blower", "Palu", "Mesin potong"],
    produk: ["Arit", "Cangkul", "Golok"],
    keterangan: "UMKM pandai besi yang memproduksi alat kerja untuk pertanian dan rumah tangga.",
    posisiTop: "20%",
    posisiLeft: "72%"
  },
  {
    id: 13,
    namaUsaha: "Pandai Besi Pak Narto",
    namaPemilik: "Pak Narto",
    lokasi: "Dusun Krasak, RT 07/RW 07",
    gmaps: "https://maps.google.com/",
    foto: "assets/img/umkm-placeholder.svg",
    kontakWA: "6281234567813",
    jamOperasional: "08.00 - 16.00 WIB",
    statusToko: "Buka setiap hari",
    medsos: {
      instagram: "-",
      facebook: "-",
      tiktok: "-"
    },
    keunggulan: "Melayani pembuatan alat dengan ukuran khusus.",
    alat: ["Tungku", "Palu", "Landasan besi", "Gerinda"],
    produk: ["Pisau", "Sabit", "Cangkul"],
    keterangan: "Pandai besi lokal dengan layanan pembuatan alat sesuai kebutuhan pelanggan.",
    posisiTop: "78%",
    posisiLeft: "50%"
  },
  {
    id: 14,
    namaUsaha: "Pandai Besi Pak Yanto",
    namaPemilik: "Pak Yanto",
    lokasi: "Dusun Krasak, RT 07/RW 08",
    gmaps: "https://maps.google.com/",
    foto: "assets/img/umkm-placeholder.svg",
    kontakWA: "6281234567814",
    jamOperasional: "08.00 - 16.00 WIB",
    statusToko: "Buka setiap hari",
    medsos: {
      instagram: "-",
      facebook: "-",
      tiktok: "-"
    },
    keunggulan: "Hasil produksi rapi dan kuat untuk penggunaan jangka panjang.",
    alat: ["Tungku pembakaran", "Palu", "Blower", "Gerinda"],
    produk: ["Cangkul", "Arit", "Parang"],
    keterangan: "UMKM ini menghasilkan alat pertanian yang banyak digunakan warga sekitar.",
    posisiTop: "66%",
    posisiLeft: "24%"
  },
  {
    id: 15,
    namaUsaha: "Pandai Besi Pak Kuat",
    namaPemilik: "Pak Kuat",
    lokasi: "Dusun Krasak, RT 08/RW 08",
    gmaps: "https://maps.google.com/",
    foto: "assets/img/umkm-placeholder.svg",
    kontakWA: "6281234567815",
    jamOperasional: "08.00 - 16.00 WIB",
    statusToko: "Buka setiap hari",
    medsos: {
      instagram: "-",
      facebook: "-",
      tiktok: "-"
    },
    keunggulan: "Mampu memperbaiki dan mengasah alat pertanian.",
    alat: ["Gerinda", "Tungku", "Palu", "Landasan"],
    produk: ["Pisau", "Sabit", "Cangkul"],
    keterangan: "Usaha pandai besi yang melayani pembuatan, perbaikan, dan pengasahan alat.",
    posisiTop: "52%",
    posisiLeft: "28%"
  }
];